# Generated by Django 5.1.2 on 2024-10-31 13:32

import agency.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spycat',
            name='breed',
            field=models.CharField(max_length=100, validators=[agency.validators.validate_breed]),
        ),
    ]
